//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBandTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        public int ID { get; set; }
        public int BANDA { get; set; }
        public string PAIS { get; set; }
        public string LUGAR { get; set; }
        public string GENERO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string LUGARCOMPRA { get; set; }
    
        public virtual BANDA BANDA1 { get; set; }
    }
}
